# Dependencies
markdown: kramdown
highlighter: pygments
url: http://www.codingapestudio.com

# Permalinks
permalink: none
relative_permalinks: true

# Title
title: CodingApe Studio

paginate: 5
paginate_path: "/blog/page:num/"
